

version: "3.3"



services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '13306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db_vol:/var/lib/mysql


#  This is the working one !!!!!!
  api:
    image: node:11
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    depends_on:
      - db
    command: bash -c "npm install && npm run dev"
    ports: 
      - 3000:3000

 
volumes:
  db_vol: 


